"""
Biological interfaces and immutable data contracts for Fruitfly V2.
Guarantees clean boundary between frozen biological systems, sensory transducers, and learned RL policy.
"""

from dataclasses import dataclass, field
import numpy as np


@dataclass(frozen=True)
class CompassState:
    """
    Immutable state snapshot emitted by the Frozen CANN Central Complex compass.
    Cannot be modified by external policies.
    """
    heading: float            # Decoded azimuth theta in [-pi, pi)
    sin_heading: float        # sin(theta) (smooth cyclic representation)
    cos_heading: float        # cos(theta)
    coherence: float          # Bump quality in [0, 1]
    amplitude: float          # Vector sum amplitude
    torque: float             # Differential P-EN activation (Right - Left)
    epg_activity: np.ndarray  # Shape (48,), normalized [0, 1], read-only
    pen_left_mean: float      # Left shifter activity
    pen_right_mean: float     # Right shifter activity
    pfl3_bias: float          # Biological steering bias from PFL3 in [-1, 1]

    def to_observation_vector(self) -> np.ndarray:
        """Compact 5D vector matching rl.observation_space['compass']."""
        return np.array(
            [self.sin_heading, self.cos_heading, self.coherence, self.torque, self.pfl3_bias],
            dtype=np.float32,
        )


@dataclass(frozen=True)
class SensoryState:
    """
    Immutable snapshot of biological sensory perception (chemical and visual).
    """
    odor_concentrations: np.ndarray   # Raw concentrations at antennae, shape (4,)
    al_glomeruli: np.ndarray          # Antennal Lobe rate-coded outputs, shape (4,) in [0, 1]
    canvas_bearing: float             # Egocentric bearing to canvas center in [-pi, pi)
    canvas_dist_norm: float           # Normalized distance to canvas [0, 1]
    pot_bearings: np.ndarray          # Egocentric bearings to pots R, G, B, Y in [-pi, pi), shape (4,)
    pot_distances_norm: np.ndarray    # Normalized distances to pots R, G, B, Y in [0, 1], shape (4,)
    min_pot_dist: float               # Normalized distance to closest pot in [0, 1]
    altitude_norm: float              # Normalized altitude z / z_max in [0, 1]

    def to_sensory_vector(self) -> np.ndarray:
        """Compact 8D vector matching rl.observation_space['sensory']."""
        return np.array(
            [
                self.canvas_bearing / np.pi,  # Normalized [-1, 1]
                self.canvas_dist_norm * 2.0 - 1.0,  # [-1, 1]
                self.pot_bearings[0] / np.pi,
                self.pot_bearings[1] / np.pi,
                self.pot_bearings[2] / np.pi,
                self.pot_bearings[3] / np.pi,
                self.min_pot_dist * 2.0 - 1.0,
                self.altitude_norm * 2.0 - 1.0,
            ],
            dtype=np.float32,
        )

    def to_odor_vector(self) -> np.ndarray:
        """Compact 4D vector matching rl.observation_space['odor']."""
        return np.clip(self.al_glomeruli, 0.0, 1.0).astype(np.float32)


@dataclass(frozen=True)
class BrainOutput:
    """
    Output generated by the descending biological premotor bridge.
    Controls physical kinematics of the fly body and brush actuator.
    """
    steering_omega: float             # Net angular steering velocity in rad/s
    forward_velocity: float           # Forward speed in px/s
    altitude_command: float           # Target altitude or climb rate
    pen_pressure: float               # Brush pressure in [0, 1]
    pen_down: bool                    # Physical brush contact intent


@dataclass
class BiologyConfig:
    """
    Physical and biological configuration constants for Fruitfly V2.
    """
    # Compass / CANN architecture
    n_epg: int = 48
    n_pen_side: int = 24
    n_pfl3_total: int = 24
    n_pfl3_side: int = 12
    tau_m: float = 0.016
    tau_pfl3: float = 0.025
    k_div: float = 0.012
    substeps_per_frame: int = 8
    w_ee: float = 2.4
    w_ep: float = 1.8
    w_pe_ratio: float = 2.09
    sigma_ee: float = 0.60
    shift_angle: float = np.pi / 4.0
    noise_sigma: float = 0.01
    k_turn_drive: float = 2.5
    k_pfl3_drive: float = 2.8

    # Sensory Olfaction
    sigma_odor: float = 120.0         # Spatial plume radius
    beta_odor: float = 3.0            # AL tanh gain
    n_odor_channels: int = 4          # R, G, B, Y

    # Sensory Vision
    arena_width: float = 1000.0
    arena_height: float = 1000.0

    # Motor & Kinematics
    v_cruise: float = 120.0           # Baseline cruising speed px/s
    v_min: float = 30.0
    v_max: float = 180.0
    omega_max: float = 4.5            # Max angular velocity rad/s
    omega_bias_max: float = 2.5       # Learned steering bias authority
    z_max: float = 50.0               # Max flight altitude
    z_cruise: float = 30.0            # Default cruising altitude
    z_contact: float = 2.0            # Threshold below which brush contacts canvas
    pen_flow_rate: float = 0.15       # Pigment deposition speed per sec at P=1
    pigment_capacity: float = 1.0     # Max pigment volume in brush reservoir
